### ISSUE TITLE
[WIP] Waku v2 Privacy/Anonymity Roadmap

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#107]
## Background / Motivation

One of Waku's main design goals is being privacy and anonymity preserving.
While Waku v2 is privacy-preserving, Waku v2 relay currently protects anonymity only in weak attacker models like *local attacker* and *single node attacker*.

However, Waku v2 is modular and was designed with pluggable privacy/anonymity in mind.
The following agenda of issues covers our plans to analyse current Waku v2 protocols with respect to their privacy/anonymity guarantees, as well as plans to evaluate, specify, and implement new protocols that will enhance Waku v2 privacy/anonymity.

## Issues

(This roadmap is WIP. Items on the roadmap, especially ones farther in the future, might change.)

* [x] #106
  [HackMD](https://hackmd.io/Q9Mxs-wLRwe9i0XlGKTU5g) covering the current state of Waku v2 Privacy as well as FAQ including Tor and [Briar](https://briarproject.org/how-it-works/)
* [ ] #104
* [ ] [Dandilion++](https://arxiv.org/abs/1805.11060) for Waku v2
  - [ ] check waku Dandilion++ feasibility
    - Does Dandilion++ offer the properties we want from a lightweight pluggable anonymity protocol?
    - Does the efficiency / latency cost seem acceptably low?
  - [ ] Waku-Dandilion raw RFC
  - [ ] implementation of Waku-Dandilion
  - [ ] research log post on Waku-Dandilion
* [ ] Research log post on Privacy/Anonymity properties of further Waku v2 protocols
  - store, lightpush, filter, peer-exchange, capability discovery
  - we still have to decide on scoping
  - might split into several posts
* [ ] Waku Privacy/Anonymity FAQ (to be published on website)
  Building on #106, #104, and further results from earlier issues on this roadmap
* [ ] Onion Routing for Waku v2
  - [ ] Waku over Tor raw RFC
  - [ ] Waku over Tor implementation
    - see #90
  - [ ] research log article on Waku over Tor
  - [ ] Waku onion routing protocol RFC
    - This is an ambitious goal and might be pushed further into the future.
      The reason for it being on the roadmap is the desire to be independent of other technologies.
      Also, Tor features many centralized elements.
  - [ ] implementation of Waku onion routing
  - [ ] research log article on Waku onion routing
* [ ] Mix-net support for Waku v2
  - [ ] Waku over [Nym](https://nymtech.net/) protocol RFC
  - [ ] Waku over [Nym](https://nymtech.net/) implementation
  - [ ] Waku mix-net protocol RFC
  - [ ] Implementation of Waku mix protocol
  - [ ] research log article on Waku mix-net
* [ ] censorship resistance
* [ ] comprehensive Waku v2 Privacy/Anonymity Analysis
* [ ] identify further issues
* [ ] Research Paper on Waku privacy/anonymity
