### ISSUE TITLE
[WIP] Ambient Peer Discovery Roadmap

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#116]
This issue tracks our Waku ambient peer discovery roadmap.
A discussion of these and future ideas can be found [here](https://forum.vac.dev/t/waku-v2-discv5-roadmap-discussion/121).

## Milestones

* [x] Waku Discv5 RFC, implementation, Disc5 DNS bootstrap #879
* [ ] Waku Peer Exchange
* [ ] Waku Capability Discovery/Push

## Future Issues

* [ ] enhance capability discovery / add capability advertising ([vacp2p/rfc #429](https://github.com/vacp2p/rfc/issues/429))
* [ ] discv5 : add explicit support for NAT traversal see discussion [here](https://github.com/ethereum/devp2p/issues/199)
* [ ] raw RFC: Waku2 mDNS discovery (truly decentralized local discovery)
