### ISSUE TITLE
Milestone: RLN-Relay testnet1 - dynamic group and on-chain

### ISSUE THREAD

**Issue by oskarth** [vacp2p/research#126]
## Problem

This is the second testnet for RLN-Relay. It is about being able to join the RLN group dynamically from your nwaku node, and registering on chain.

## Scope

*NOTE* The following is not necessarily a complete list, and we should prioritize making this scope as minimal but complete as possible

List of issues:

- (Many other issues were complete since testnet0 and aren't necessarily listed here)
- [x] On chain setup: https://github.com/status-im/nwaku/issues/1015
- [x] testnet preparation https://github.com/status-im/nwaku/issues/827
- [x] Tutorial https://github.com/status-im/nwaku/pull/1044
- [x] https://github.com/status-im/nwaku/pull/1037
- [x] Announce to relevant parties (e.g. #vac-pm? or more open group) to start dogfooding with clear actions
- [x] At least ~5 people participating and providing feedback
- [x] Feedbacks are addressed or captured as GH issues

## Risks and uncertainty

- New components bring additional risks and complications. The on-chain model and dynamic group management model is new and there are likely several kinks to work out.
- Exact scope is currently variable and needs to be cut/minimized (however this seems doable)
- Some unknowns regarding contract and spec thereof (though probably good enough for testnet)

In terms of timelines expect this testnet to conclude by mid August (TODO: to be confirmed).

## Acceptance criteria

Issues defined in scope addressed. Testnet has been run by multiple participants and feedback has been gathered and captured.

## Out of scope

- Performance work
- Zerokit integration
- ERC20 usage
- Multi client testnet

## Future steps

- Make testnet2 scope clear (mutli-client, including dependency on e.g. js-waku integration; ERC20 integration etc)
- Understand performance work needed and scope this
- Ensure testnets are integrated with operator-outreach and invite multiple participants, write-up etc
- Have an understanding of when an audit and trusted setup would be needed

**Comment by oskarth** [comment]
@staheri14 I wrote this up as a stub, please edit it to make it more complete and make any corrections necessary here.

cc @s1fr0 @kgrgpg

**Comment by oskarth** [comment]
The owner/assignee is the main person responsible for the milestone outcome

**Comment by oskarth** [comment]
@staheri14 please edit the above issue so you are happy with this. There are some mentions of TODOs that should either be filled out and remove.

I see you highlighted a few individuals in the dogfooding channel, is there a specific timeline for when you expect this to run and feedback to be collected? Say, this week? And then collect the feedback somewhere to conclude this milestone.

**Comment by oskarth** [comment]
@staheri14 what's left for this milestone to be considered done?

**Comment by staheri14** [comment]
@oskarth The feedbacks of the first testnet are yet to be incorporated (see the tracking issue https://github.com/status-im/nwaku/issues/1069).  However, since all the items in this issue are covered, I think we can consider the first testnet concluded.
