### ISSUE TITLE
Milestone: launch Waku operator trial amongst core contributors

### ISSUE THREAD

**Issue by jm-clius** [vacp2p/research#133]
## Problem

We want to push for operators to run and maintain their own Waku v2 nodes, preferably contributing to the default Waku v2 network as described by the default pubsub topic (`/waku/2/default-waku/proto`). Amongst other things, a large fleet of stable operator-run Waku v2 nodes will help secure the network, provide valuable services to a variety of platforms and ensure the future sustainability of both Vac as a research organization and the Waku suite of protocols.

As a first step we want to launch an operator trial among core contributors, volunteer community members and team members where participants run their own long-lived Waku nodes:
1. participating in the default `relay` network
2. optionally providing `store`, `filter` and `lightpush` functionality.

## How many trial operators do we want?

Within Q3 2022 we want to have at least **8-10** additional operator-run nodes added to the network during the trial period. The hope is that this number will rapidly rise as more contributors and community members come on board.

## Who will be targeted?

Anyone will be free to participate and we'll advertise the trial as widely as possible, but we'll also specifically:
- ask all Vac team members to participate
- invite the larger Status community to participate
- invite the existing Waku community to participate

## What Waku clients will participate?

The trial and tutorials will be directed at `nwaku` clients, but operators can use any Waku client to participate.

## List of open issues

- [ ] https://github.com/status-im/nwaku/issues/1003
- [ ] https://github.com/status-im/nwaku/issues/828

## Risks and uncertainty

Those likeliest to contribute first (i.e. team members, core contributors) may not have the hardware/cloud computing resources necessary to maintain long-lived Waku nodes. This milestone will be "done" when the trial has been successfully launched, not when we have reached a certain amount of stable nodes in the network.

## Acceptance criteria

- [ ] Scope issues addressed

## Out of scope

- Reaching a target network size (this is a focus of the track - this milestone focuses simply on launching the trial)
- Adding a monitoring node to the network to monitor network size and other growth statistics (should be separate milestone)
- Reporting network growth metrics (should be separate milestone)

## Notes and links

More details at https://hackmd.io/l9eFrUeiSkeQbIFmk2NzAQ#Tracks

**Comment by jm-clius** [comment]
> Note: this issue has been recreated from a similar issue in a private repo (it's not possible to transfer issues from a private to a public repo, hence the recreation).

**Comment by jm-clius** [comment]
Comment from @oskarth previously:

> Nicely scoped issue. Few points:
> 
> 1) Should this issue be in a private repo like pm? If it isn't sensitive, I suggest we keep it in research repo as a public issue
> 2) Can we involve RLN testnet here somehow? @staheri14 
> 3) Discovery and NAT traversal etc seems like a risk to me, but maybe we're confident in this already?
> - related to this is browser experience and it being useful as service nodes, but maybe we feel this has too many other dependencies? @fryorcraken 
> 4) Does it make sense to involve go-waku and Status desktop? @richard-ramos 
> 5) It'd be good to make sure we capture feedback and get on some regular cadence here, so we can use as input for next "push" in this

(1) has been addressed by recreating this issue in a public repo
