### ISSUE TITLE
Milestone:  Waku Tor Push

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#149]
This milestone issue tracks Tor push for Waku v2. It is part of #107

## Problem

Currently, Waku's sender anonymity properties are relatively weak.
Tor push allows nodes to push Waku messages via Tor into the Walu relay network,
providing significant sender anonymity gains.

## Scope

List of issues:

* [x] #172
* [x] #173
* [ ] Waku Tor push PoC
* [ ] implementation of Waku Tor push
* [ ] research log post on Waku Tor push

## Acceptance criteria

All issues listed above have to be completed.

## Notes and links

related to #90
