### ISSUE TITLE
Roadmap(SeM): Secure Scaling

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#154]
## Issues

(This roadmap is WIP. Items on the roadmap, especially ones farther in the future, might change.)

### Simple scaling to 1 mio users

* [x] #163
  - [x] #174
    - https://github.com/vacp2p/rfc/pull/576
    - https://github.com/vacp2p/rfc/pull/579
    - https://github.com/vacp2p/rfc/pull/583
  - [x] #178
* [x] #160
* [x] #158
* [x] #164
   - [x] https://github.com/vacp2p/research/issues/148
   - [x] https://github.com/vacp2p/research/issues/141

[Overview over the integration of these tasks into the Status MVP](https://github.com/waku-org/pm/issues/12#issuecomment-1403577619)

### mid/long-term Research
* [x] #157
* [ ]  #159
* [x] Waku Relay DoS mitigation
* [ ] Scaling a single Waku Relay mesh
* [ ] New Message Dissemination Methods
  - alternatives to Waku Relay, with different desirable trade-offs
