### ISSUE TITLE
Roadmap(SeM): RLNP2P

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#179]
### RLNP2P general

> *Note*: This roadmap is WIP. Items on the roadmap, especially ones farther in the future, might change.

[Timeline and prios for next months, incl. implementation](https://hackmd.io/QM0hkxBFREKQODEXrQEA6Q)

* [x] https://github.com/Rate-Limiting-Nullifier/rln-circuits/issues/1
* [ ] https://github.com/vacp2p/rfc/pull/550
* [ ] new RFC: RLN contract
* [x] https://github.com/vacp2p/zerokit/issues/70
* [x] https://github.com/vacp2p/rfc/issues/571

### RLN/waku-rln-relay

* [x] 32/RLN:  https://github.com/vacp2p/rfc/issues/556
  - with PSE
* [x] RLN security audit
  - [scope](https://hackmd.io/5DDt1wU4QEmdZOs_Evx2gg)
  - *blocker*: currently planned changes to the RLN contract

### Future Work

---

@rymnc

**Comment by rymnc** [comment]
Update: as per the retrospective of rln-testnet-3, the follows issues were identified and will be worked upon to bring rln ready for use with waku -
- [ ] https://github.com/waku-org/nwaku/issues/1772
- [ ] https://github.com/waku-org/nwaku/issues/1773
- [ ] https://github.com/waku-org/nwaku/issues/1775

cc: @kaiserd @jm-clius

**Comment by rymnc** [comment]
By closing all the issues identified from the retrospective, the rlnp2p team will start working towards the requirements specific to waku product, like static memberships etc. Issues will be created in the vacp2p/rln-contract repo.

**Comment by rymnc** [comment]
Issues identified for the waku public network:
- https://github.com/waku-org/nwaku/issues/1837
- https://github.com/waku-org/nwaku/issues/1836
