### ISSUE TITLE
SeM(Milestone): Scaling Status App to 1 million users MVP

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#187]
This milestone issue captures SeM tasks for the Status 1 million users MVP.
It stretches over several SeM tracks, among them [Secure Scaling](https://github.com/vacp2p/research/issues/154), [Application Protocols](https://github.com/vacp2p/research/issues/165), [Discovery](https://github.com/vacp2p/research/issues/116), and [Data Sync](https://github.com/vacp2p/research/issues/170).

This issue is related to the [Waku 10k milestone](https://github.com/waku-org/pm/issues/12).

## Waku Relay Scaling Plan

The general task for SeM is to come up with a simple scaling strategy that allows scaling a Waku network to 1 million users.
The basis of our idea is sharding the Waku relay network, i.e. using several pubsub meshes instead of a single one.
To keep up with the tight timeline for this MVP, trade-offs to privacy&anonymity have to be made.

Our goal is achieving 10k users in a single shard and scaling the network to 1 million users using multiple shards.
In the context of this milestone, this limits the size of a single multicast group (and by extension the size of a single community) to 10k active users.

SeM work towards the MVP is split into tree main tasks

1) scaling a single shard (pubsub mesh) to 10k users.
Our [simple model](https://hackmd.io/IYmyyUIdSEuRZ7WbYd6dng?view) we developed as part of this scaling plan showed:
current Waku relay should theoretically already be able to scale to 10k nodes per shard.
Our main focus here is identifying practical issues as well as problems arising from the way Status currently [uses Waku Relay](https://github.com/vacp2p/research/issues/177).

2) scaling the Waku network used by Status App to 1 million users (assuming we solved 1).
Our focus here is coming up an easy-to-deploy approach that allows discovering nodes associated with a subset of a set of ~1000 shards.
We need at least 100 shards for communities and another 100 shards for 1:1 chats.
[Here](https://rfc.vac.dev/spec/51/) is the current version of our relay sharing RFC.
For the Status 1 million users MVP, we will use the *static sharding* method specified in this RFC.
Other work here comprises ways of mapping Status communities to shards.

3) specifications for both Status protocols and scaling extensions for Waku protocols.

Regarding the store protocol, we pursue a simple approach for the MVP:
store nodes are federated and provided by the respective community; they cover each content topic within the respective community.
We can also add powerful infrastructure store nodes that cover all pubsub meshes relevant to the Status app.
The work on store towards the MVP is mainly driven by the Waku product team.

owner: @kaiserd

## Waku Relay Scalability Analysis

* [x] #158
 - (we might extend the model / analysis based on requirements)
* [ ] add model case for community control messages
* [ ] add model case for flood-publish (if significant)

owner: @kaiserd

## Discovery

We are working on improvements and simplifications of the static sharding method.

* [topic sharding improvements](https://github.com/vacp2p/research/issues/174)

owner: @kaiserd

## DoS mitigation

* [x] #164

owner: @alrevuelta

## Communities

* [x] extract how Status communities work as a basis for a specification (from code and asking CCs)
  - main work here is done modulo some clarifications and follow-ups
* [ ] identify scaling problems
  - current status: #177

owner: @rymnc 

## 1:1 chat
* [x] extract how Status 1:1 chat works as a basis for a specification (from code and asking CCs)
  - main work here is done modulo some clarifications and follow-ups
* [ ] identify scaling problems

owner: @rymnc 

## Status App Protocols Mapping

* research for: #167

owner: @rymnc, @kaiserd

## RFCs

* [x] #163
  - (we are still working on improvements here)
* [x] #166
* [x] #168
* [x] #160
  - [x] #167
  - [ ] Dos Mitigation ( #164 ) will be part of this RFC

owner: @kaiserd, @rymnc, @alrevuelta

We plan to publish each of these RFCs (at least in raw status) by the end of Q1 2023.

CC @cammellos @felicio @fryorcraken @oskarth @corpetty @john-44

**Comment by rymnc** [comment]
Additional RFC to be included in this milestone (59/STATUS-URL-DATA) ([PR](https://github.com/vacp2p/rfc/pull/600)) - 

https://github.com/status-im/specs/pull/159#issuecomment-1546918204

**Comment by felicio** [comment]
> Additional RFC to be included in this milestone (59/STATUS-URL-DATA) ([PR](https://github.com/vacp2p/rfc/pull/600)) -
> 
> [status-im/specs#159 (comment)](https://github.com/status-im/specs/pull/159#issuecomment-1546918204)

- https://github.com/vacp2p/rfc/pull/600
- https://github.com/vacp2p/rfc/pull/602
