### ISSUE TITLE
Roadmap(DR): Validator Privacy

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#190]
# Validator Privacy

*This is part of the Vac Deep Research, Anonymity&Privacy branch.*

*this roadmap is WIP*

## Tor Push

Background and motivation [here](https://ethresear.ch/t/a-tor-based-validator-anonymity-approach-incl-comparison-to-dandelion/14134).

* [x] comprehensive current/related work study on *Validator Privacy*
   - focus on network layer but also including: network vs consesus layer privacy (SSLE), as well as combinations
* [x] PoC of [Tor push](https://rfc.vac.dev/spec/46/) in Nimbus (testnet Goerli) https://github.com/vacp2p/nimbus-eth2-experimental/issues/1
   - first latency measurements (comprehensive analysis in next milestone)
   - research log post on Tor push / Nimbus PoC incl first latency measurements
   - update/adjust Tor push spec
   - talk @ Logos research call
* [ ] thorough anonymity/sec analysis of Tor push for Validator privacy
* [ ] thorough latency analysis of Tor push
* [ ] paper (for workshop) on introducing and analysing Tor-push
* [ ] employ RLN for rate limiting

## Privacy Preserving Node Provider Network

Goal: a privacy preserving and decentralized alternative to current node providers.
Tor push + RLN, explored in the previous step, will serve as component in the Privacy Preserving Node Provider network.

* [ ] EF proposal joint with chainsafe.
* [ ] ...
* [ ] incentivize adding nodes to the network
* [ ] ...

## Custom Onion Routing / Mix-Net Solution

(potentially in the future)

* discussion in Validator Privacy Discord

## Nomos Integration

(future work)

**Comment by ujscale** [comment]
Integrating TorSwitch within nimbus ..another approach

https://github.com/vacp2p/nimbus-eth2-experimental/pull/2

**Comment by ujscale** [comment]
These are working changes that are able to send messages (attestation, block) over Tor
[Fixing init for torPeers, Adding async tor connection, Adding log msgs](https://github.com/vacp2p/nimbus-eth2-experimental/pull/2/commits/431a76014b3f584573329993b167fe1118eca6b3)
Only tested the sender side so far. Still to do further testing

**Comment by ujscale** [comment]
This [commit](https://github.com/vacp2p/nimbus-eth2-experimental/commit/568da80e1a6c89685c2dddbd3d4c90f42b187372) provides the first tor based gossipsub instance usage with in nimbus to broadcast attestations over tor.
The validator was successfully run based on this and stats were collected

[Stats collected](https://drive.google.com/drive/folders/1_A3wCIpLd8IpBuguHZL-iyhY6wQ_cCNg)
[Validator](https://goerli.beaconcha.in/validator/86f53cc0e56ae0c6fbe3113a290a52a76cf056339d91f9e166ddbf15a35373d3c455cc387c8ab70db7b3d024113e394d#attestations)
