### ISSUE TITLE
Roadmap(Nescience)

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#193]
## Evaluating proof systems and related work

* [ ] #197
  - [x] Main document highlighting differences
  - [x] Add halo2 differences and explanation
  - [ ] Add different types of recursion
  - [x] Add Arecibo (SuperNova)

* [ ] #198
  - [x] Specs for benchmarking plonky2, starky2, halo2 and nova
  - [x] Recursive circuit for Nova (recursively calling Poseidon hashing)
  - [ ] Recursive circuit for Halo2 GWC 
  - [ ] Recursive circuit for Halo2 SHPLONK
  - [ ] Recursive circuit for Arecibo
  - [ ] Vac research log post on proof system benchmarks
  - [ ] Scientific paper on proof system benchmarks

## Nescience zkVM

* [x] #202
* [ ] toy zkVM (using proof system with best benchmark results, see above)

### Towards the zkVM (more task granularity will be added step by step)
* [ ] zkVM formal proposal including architecture, execution trace proof(s) and memory proof(s)
* [ ] #203
