### ISSUE TITLE
Umbrella issue: Understand and use BlockScience model

### ISSUE THREAD

**Issue by oskarth** [vacp2p/research#33]
## Problem

We currently have an economic model on incentivized routing/storage. However, it is divorced from existing systems. We need to understand it in more detail, see how we can use it, where it is disconnected from reality, what assumptions it makes, what implications it has for topology, etc etc.

## Suggest approach

This is a meta-issue for different ways of approach this problem. There are a few different ways of approach this, and this issue will link to these.

- [ ] Break the model https://github.com/vacp2p/research/issues/34
- [ ] Map API to existing routing
- [ ] Define precise experiments to run (and run them)
- [ ] Define precise questions to ask BS (and ask them)
- [ ] Get intuition to question and inform test plan priority order
- [ ] Understand what assumptions models are making that doesn't map to reality
- [ ] Sketch out how to plug model into e.g. existing Kad
- [ ] Sketch out a feasibility plan for integration with core app (can we integrate this? and roughtly how? what are the unknowns
- [ ] Find the highest risk assumptions and test those against a real world scenario (latency etc)

As well as splitting this work over a few different people.

## Acceptance criteria

Sufficient understanding and clear next steps for how to work with this model. Likely includes several, but possibly not all, of the points above.
